### PR TITLE
Fix xcode 11 3 output

### LINKED ISSUE #27: Fail to output properly on Xcode 11.3
Hi @thii,

We encounter this issue again since you fixed the same issue (#23 ) for Xcode 11.2... Unstable format of xcodebuild output is a real headache for xcbeautify.

Could you take a look?

### PR DESCRIPTION
**Pull request by greensky01**
This submission is to fix incorrect output of compile command. 

Firstly, compile command parser is different than other "compile" parsers because it has only 2 parsed groups. Therefore I added a separate formatCompileCommand(...) to handle this case.

Secondly, the compile command is kind of detailed message. For the most cases, one might not need to check it. To this end, I added a command line option to control how verbose xcbeautify should be. Please note, now quiet mode is equivalent to "--verbose 1" mode.

Resolves https://github.com/thii/xcbeautify/issues/27.

### CODE REVIEW

**Comment by greensky01** [comment]
Hi @thii, I fixed the compile command issue. And also I added a verbosity option. From my point of view, providing 3 levels of verbosity is enough, although maybe you have more reasonable thoughts to provide more.

Please review the code and leave any comments you want.

File: Sources/XcbeautifyLib/String+Beautify.swift [hunk 1]
```diff
@@ -196,6 +197,13 @@ extension String {
         return _colored ? "[\(target.f.Cyan)] \("Processing".s.Bold) \(filename)" : "[\(target)] Processing \(filename)"
     }
 
+    private func formatCompileCommand(pattern: Pattern) -> String? {
+        let groups = capturedGroups(with: pattern)
+        let leading = "Compile Command For"
+        let command = groups[0]
+        guard let filePath = groups.last else { return nil }
+        return "\(leading.s.Bold) \(filePath):\n\(command)"
```
Comment (thii) [inline Sources/XcbeautifyLib/String+Beautify.swift]: What would this print for your example? Have you taken a look at how xcpretty parse this?

Comment (greensky01) [reply Sources/XcbeautifyLib/String+Beautify.swift]: For the same file, sample.txt,

`cat sample.txt | xcpretty`
 will output:
Compiling Stdafx.cpp

`cat sample.txt | xcbeautify` 
will output:
[TargetName] Compiling Stdafx.cpp

`cat sample.txt | xcbeautify -V 3`
will output:
```
[TargetName] Compiling Stdafx.cpp
Compile Command For /Path/to/Stdafx.cpp:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -target blablabla ....
```

Comment (thii) [reply Sources/XcbeautifyLib/String+Beautify.swift]: I really appreciate you took time to implement the verbose feature, but I think we can just ignore the detail compile command output, the same way `xcpretty` does, since it's the purpose of using a beautifier tool to begin with. Users can always use the `tee` command to pipe the raw xcodebuild output somewhere if they want more detailed output.

Comment (greensky01) [reply Sources/XcbeautifyLib/String+Beautify.swift]: I totally understand what you say and agree xcbeautify should keep simple :) By "ignoring the detail compile command", do you mean return nil from formatCompileCommand?

Comment (thii) [reply Sources/XcbeautifyLib/String+Beautify.swift]: That's right.

Comment (greensky01) [reply Sources/XcbeautifyLib/String+Beautify.swift]: I've updated code. Please review.

**Review by thii — APPROVED** [review]

**Comment by thii** [comment]
This was released as part of 0.7.2. Thanks again!
